<?php

use Illuminate\Database\Seeder;

class ProvinceTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cities')->insert(['id' => '1105', 'name' => 'Aceh Barat']);
        DB::table('cities')->insert(['id' => '1112', 'name' => 'Aceh Barat Daya']);
        DB::table('cities')->insert(['id' => '1106', 'name' => 'Aceh Besar']);
        DB::table('cities')->insert(['id' => '1114', 'name' => 'Aceh Jaya']);
        DB::table('cities')->insert(['id' => '1101', 'name' => 'Aceh Selatan']);
        DB::table('cities')->insert(['id' => '1110', 'name' => 'Aceh Singkil']);
        DB::table('cities')->insert(['id' => '1116', 'name' => 'Aceh Tamiang']);
        DB::table('cities')->insert(['id' => '1104', 'name' => 'Aceh Tengah']);
        DB::table('cities')->insert(['id' => '1102', 'name' => 'Aceh Tenggara']);
        DB::table('cities')->insert(['id' => '1103', 'name' => 'Aceh Timur']);
        DB::table('cities')->insert(['id' => '1108', 'name' => 'Aceh Utara']);
        DB::table('cities')->insert(['id' => '1306', 'name' => 'Agam']);
        DB::table('cities')->insert(['id' => '5305', 'name' => 'Alor']);
        DB::table('cities')->insert(['id' => '8171', 'name' => 'Ambon']);
        DB::table('cities')->insert(['id' => '1209', 'name' => 'Asahan']);
        DB::table('cities')->insert(['id' => '9304', 'name' => 'Asmat']);
        DB::table('cities')->insert(['id' => '5103', 'name' => 'Badung']);
        DB::table('cities')->insert(['id' => '6311', 'name' => 'Balangan']);
        DB::table('cities')->insert(['id' => '6471', 'name' => 'Balikpapan']);
        DB::table('cities')->insert(['id' => '1171', 'name' => 'Banda Aceh']);
        DB::table('cities')->insert(['id' => '1871', 'name' => 'Bandar Lampung']);
        DB::table('cities')->insert(['id' => '3273', 'name' => 'Bandung']);
        DB::table('cities')->insert(['id' => '3217', 'name' => 'Bandung Barat']);
        DB::table('cities')->insert(['id' => '7201', 'name' => 'Banggai']);
        DB::table('cities')->insert(['id' => '7207', 'name' => 'Banggai Kepulauan']);
        DB::table('cities')->insert(['id' => '7211', 'name' => 'Banggai Laut']);
        DB::table('cities')->insert(['id' => '1901', 'name' => 'Bangka']);
        DB::table('cities')->insert(['id' => '1905', 'name' => 'Bangka Barat']);
        DB::table('cities')->insert(['id' => '1903', 'name' => 'Bangka Selatan']);
        DB::table('cities')->insert(['id' => '1904', 'name' => 'Bangka Tengah']);
        DB::table('cities')->insert(['id' => '3526', 'name' => 'Bangkalan']);
        DB::table('cities')->insert(['id' => '5106', 'name' => 'Bangli']);
        DB::table('cities')->insert(['id' => '3279', 'name' => 'Banjar']);
        DB::table('cities')->insert(['id' => '6372', 'name' => 'Banjarbaru']);
        DB::table('cities')->insert(['id' => '6371', 'name' => 'Banjarmasin']);
        DB::table('cities')->insert(['id' => '3304', 'name' => 'Banjarnegara']);
        DB::table('cities')->insert(['id' => '7303', 'name' => 'Bantaeng']);
        DB::table('cities')->insert(['id' => '3402', 'name' => 'Bantul']);
        DB::table('cities')->insert(['id' => '1607', 'name' => 'Banyuasin']);
        DB::table('cities')->insert(['id' => '3302', 'name' => 'Banyumas']);
        DB::table('cities')->insert(['id' => '3510', 'name' => 'Banyuwangi']);
        DB::table('cities')->insert(['id' => '6304', 'name' => 'Barito Kuala']);
        DB::table('cities')->insert(['id' => '6204', 'name' => 'Barito Selatan']);
        DB::table('cities')->insert(['id' => '6213', 'name' => 'Barito Timur']);
        DB::table('cities')->insert(['id' => '6205', 'name' => 'Barito Utara']);
        DB::table('cities')->insert(['id' => '7311', 'name' => 'Barru']);
        DB::table('cities')->insert(['id' => '2171', 'name' => 'Batam']);
        DB::table('cities')->insert(['id' => '3325', 'name' => 'Batang']);
        DB::table('cities')->insert(['id' => '1504', 'name' => 'Batanghari']);
        DB::table('cities')->insert(['id' => '3579', 'name' => 'Batu']);
        DB::table('cities')->insert(['id' => '1219', 'name' => 'Batu Bara']);
        DB::table('cities')->insert(['id' => '7472', 'name' => 'Bau Bau']);
        DB::table('cities')->insert(['id' => '3275', 'name' => 'Bekasi']);
        DB::table('cities')->insert(['id' => '1902', 'name' => 'Belitung']);
        DB::table('cities')->insert(['id' => '1906', 'name' => 'Belitung Timur']);
        DB::table('cities')->insert(['id' => '5304', 'name' => 'Belu']);
        DB::table('cities')->insert(['id' => '1117', 'name' => 'Bener Meriah']);
        DB::table('cities')->insert(['id' => '1403', 'name' => 'Bengkalis']);
        DB::table('cities')->insert(['id' => '6107', 'name' => 'Bengkayang']);
        DB::table('cities')->insert(['id' => '1771', 'name' => 'Bengkulu']);
        DB::table('cities')->insert(['id' => '1701', 'name' => 'Bengkulu Selatan']);
        DB::table('cities')->insert(['id' => '1709', 'name' => 'Bengkulu Tengah']);
        DB::table('cities')->insert(['id' => '1703', 'name' => 'Bengkulu Utara']);
        DB::table('cities')->insert(['id' => '6403', 'name' => 'Berau']);
        DB::table('cities')->insert(['id' => '9106', 'name' => 'Biak Numfor']);
        DB::table('cities')->insert(['id' => '5206', 'name' => 'Bima']);
        DB::table('cities')->insert(['id' => '1275', 'name' => 'Binjai']);
        DB::table('cities')->insert(['id' => '2101', 'name' => 'Bintan']);
        DB::table('cities')->insert(['id' => '1111', 'name' => 'Bireuen']);
        DB::table('cities')->insert(['id' => '7172', 'name' => 'Bitung']);
        DB::table('cities')->insert(['id' => '3505', 'name' => 'Blitar']);
        DB::table('cities')->insert(['id' => '3316', 'name' => 'Blora']);
        DB::table('cities')->insert(['id' => '7502', 'name' => 'Boalemo']);
        DB::table('cities')->insert(['id' => '3201', 'name' => 'Bogor']);
        DB::table('cities')->insert(['id' => '3522', 'name' => 'Bojonegoro']);
        DB::table('cities')->insert(['id' => '7101', 'name' => 'Bolaang Mongondow']);
        DB::table('cities')->insert(['id' => '7111', 'name' => 'Bolaang Mongondow Selatan']);
        DB::table('cities')->insert(['id' => '7110', 'name' => 'Bolaang Mongondow Timur']);
        DB::table('cities')->insert(['id' => '7108', 'name' => 'Bolaang Mongondow Utara']);
        DB::table('cities')->insert(['id' => '7406', 'name' => 'Bombana']);
        DB::table('cities')->insert(['id' => '3511', 'name' => 'Bondowoso']);
        DB::table('cities')->insert(['id' => '7308', 'name' => 'Bone']);
        DB::table('cities')->insert(['id' => '7503', 'name' => 'Bone Bolango']);
        DB::table('cities')->insert(['id' => '6474', 'name' => 'Bontang']);
        DB::table('cities')->insert(['id' => '9302', 'name' => 'Boven Digoel']);
        DB::table('cities')->insert(['id' => '3309', 'name' => 'Boyolali']);
        DB::table('cities')->insert(['id' => '3329', 'name' => 'Brebes']);
        DB::table('cities')->insert(['id' => '1375', 'name' => 'Bukittinggi']);
        DB::table('cities')->insert(['id' => '5108', 'name' => 'Buleleng']);
        DB::table('cities')->insert(['id' => '7302', 'name' => 'Bulukumba']);
        DB::table('cities')->insert(['id' => '6501', 'name' => 'Bulungan']);
        DB::table('cities')->insert(['id' => '1508', 'name' => 'Bungo']);
        DB::table('cities')->insert(['id' => '7205', 'name' => 'Buol']);
        DB::table('cities')->insert(['id' => '8104', 'name' => 'Buru']);
        DB::table('cities')->insert(['id' => '8109', 'name' => 'Buru Selatan']);
        DB::table('cities')->insert(['id' => '7404', 'name' => 'Buton']);
        DB::table('cities')->insert(['id' => '7415', 'name' => 'Buton Selatan']);
        DB::table('cities')->insert(['id' => '7414', 'name' => 'Buton Tengah']);
        DB::table('cities')->insert(['id' => '7410', 'name' => 'Buton Utara']);
        DB::table('cities')->insert(['id' => '3207', 'name' => 'Ciamis']);
        DB::table('cities')->insert(['id' => '3203', 'name' => 'Cianjur']);
        DB::table('cities')->insert(['id' => '3301', 'name' => 'Cilacap']);
        DB::table('cities')->insert(['id' => '3672', 'name' => 'Cilegon']);
        DB::table('cities')->insert(['id' => '3277', 'name' => 'Cimahi']);
        DB::table('cities')->insert(['id' => '3274', 'name' => 'Cirebon']);
        DB::table('cities')->insert(['id' => '1211', 'name' => 'Dairi']);
        DB::table('cities')->insert(['id' => '9408', 'name' => 'Deiyai']);
        DB::table('cities')->insert(['id' => '1207', 'name' => 'Deli Serdang']);
        DB::table('cities')->insert(['id' => '3321', 'name' => 'Demak']);
        DB::table('cities')->insert(['id' => '5171', 'name' => 'Denpasar']);
        DB::table('cities')->insert(['id' => '3276', 'name' => 'Depok']);
        DB::table('cities')->insert(['id' => '1310', 'name' => 'Dharmasraya']);
        DB::table('cities')->insert(['id' => '9406', 'name' => 'Dogiyai']);
        DB::table('cities')->insert(['id' => '5205', 'name' => 'Dompu']);
        DB::table('cities')->insert(['id' => '7203', 'name' => 'Donggala']);
        DB::table('cities')->insert(['id' => '1472', 'name' => 'Dumai']);
        DB::table('cities')->insert(['id' => '1611', 'name' => 'Empat Lawang']);
        DB::table('cities')->insert(['id' => '5308', 'name' => 'Ende']);
        DB::table('cities')->insert(['id' => '7316', 'name' => 'Enrekang']);
        DB::table('cities')->insert(['id' => '9203', 'name' => 'Fak Fak']);
        DB::table('cities')->insert(['id' => '5306', 'name' => 'Flores Timur']);
        DB::table('cities')->insert(['id' => '3205', 'name' => 'Garut']);
        DB::table('cities')->insert(['id' => '1113', 'name' => 'Gayo Lues']);
        DB::table('cities')->insert(['id' => '5104', 'name' => 'Gianyar']);
        DB::table('cities')->insert(['id' => '7501', 'name' => 'Gorontalo']);
        DB::table('cities')->insert(['id' => '7505', 'name' => 'Gorontalo Utara']);
        DB::table('cities')->insert(['id' => '7306', 'name' => 'Gowa']);
        DB::table('cities')->insert(['id' => '3525', 'name' => 'Gresik']);
        DB::table('cities')->insert(['id' => '3315', 'name' => 'Grobogan']);
        DB::table('cities')->insert(['id' => '6210', 'name' => 'Gunung Mas']);
        DB::table('cities')->insert(['id' => '3403', 'name' => 'Gunungkidul']);
        DB::table('cities')->insert(['id' => '1278', 'name' => 'Gunungsitoli']);
        DB::table('cities')->insert(['id' => '8201', 'name' => 'Halmahera Barat']);
        DB::table('cities')->insert(['id' => '8204', 'name' => 'Halmahera Selatan']);
        DB::table('cities')->insert(['id' => '8202', 'name' => 'Halmahera Tengah']);
        DB::table('cities')->insert(['id' => '8206', 'name' => 'Halmahera Timur']);
        DB::table('cities')->insert(['id' => '8203', 'name' => 'Halmahera Utara']);
        DB::table('cities')->insert(['id' => '6306', 'name' => 'Hulu Sungai Selatan']);
        DB::table('cities')->insert(['id' => '6307', 'name' => 'Hulu Sungai Tengah']);
        DB::table('cities')->insert(['id' => '6308', 'name' => 'Hulu Sungai Utara']);
        DB::table('cities')->insert(['id' => '1216', 'name' => 'Humbang Hasundutan']);
        DB::table('cities')->insert(['id' => '1404', 'name' => 'Indragiri Hilir']);
        DB::table('cities')->insert(['id' => '1402', 'name' => 'Indragiri Hulu']);
        DB::table('cities')->insert(['id' => '3212', 'name' => 'Indramayu']);
        DB::table('cities')->insert(['id' => '9407', 'name' => 'Intan Jaya']);
        DB::table('cities')->insert(['id' => '3173', 'name' => 'Jakarta Barat']);
        DB::table('cities')->insert(['id' => '3171', 'name' => 'Jakarta Pusat']);
        DB::table('cities')->insert(['id' => '3174', 'name' => 'Jakarta Selatan']);
        DB::table('cities')->insert(['id' => '3175', 'name' => 'Jakarta Timur']);
        DB::table('cities')->insert(['id' => '3172', 'name' => 'Jakarta Utara']);
        DB::table('cities')->insert(['id' => '1571', 'name' => 'Jambi']);
        DB::table('cities')->insert(['id' => '9103', 'name' => 'Jayapura']);
        DB::table('cities')->insert(['id' => '9501', 'name' => 'Jayawijaya']);
        DB::table('cities')->insert(['id' => '3509', 'name' => 'Jember']);
        DB::table('cities')->insert(['id' => '5101', 'name' => 'Jembrana']);
        DB::table('cities')->insert(['id' => '7304', 'name' => 'Jeneponto']);
        DB::table('cities')->insert(['id' => '3320', 'name' => 'Jepara']);
        DB::table('cities')->insert(['id' => '3517', 'name' => 'Jombang']);
        DB::table('cities')->insert(['id' => '9208', 'name' => 'Kaimana']);
        DB::table('cities')->insert(['id' => '1401', 'name' => 'Kampar']);
        DB::table('cities')->insert(['id' => '6203', 'name' => 'Kapuas']);
        DB::table('cities')->insert(['id' => '6106', 'name' => 'Kapuas Hulu']);
        DB::table('cities')->insert(['id' => '3313', 'name' => 'Karanganyar']);
        DB::table('cities')->insert(['id' => '5107', 'name' => 'Karangasem']);
        DB::table('cities')->insert(['id' => '3215', 'name' => 'Karawang']);
        DB::table('cities')->insert(['id' => '2102', 'name' => 'Karimun']);
        DB::table('cities')->insert(['id' => '1206', 'name' => 'Karo']);
        DB::table('cities')->insert(['id' => '6206', 'name' => 'Katingan']);
        DB::table('cities')->insert(['id' => '1704', 'name' => 'Kaur']);
        DB::table('cities')->insert(['id' => '6111', 'name' => 'Kayong Utara']);
        DB::table('cities')->insert(['id' => '3305', 'name' => 'Kebumen']);
        DB::table('cities')->insert(['id' => '3506', 'name' => 'Kediri']);
        DB::table('cities')->insert(['id' => '9111', 'name' => 'Keerom']);
        DB::table('cities')->insert(['id' => '3324', 'name' => 'Kendal']);
        DB::table('cities')->insert(['id' => '7471', 'name' => 'Kendari']);
        DB::table('cities')->insert(['id' => '1708', 'name' => 'Kepahiang']);
        DB::table('cities')->insert(['id' => '2105', 'name' => 'Kepulauan Anambas']);
        DB::table('cities')->insert(['id' => '8107', 'name' => 'Kepulauan Aru']);
        DB::table('cities')->insert(['id' => '1309', 'name' => 'Kepulauan Mentawai']);
        DB::table('cities')->insert(['id' => '1410', 'name' => 'Kepulauan Meranti']);
        DB::table('cities')->insert(['id' => '7103', 'name' => 'Kepulauan Sangihe']);
        DB::table('cities')->insert(['id' => '7301', 'name' => 'Kepulauan Selayar']);
        DB::table('cities')->insert(['id' => '3101', 'name' => 'Kepulauan Seribu']);
        DB::table('cities')->insert(['id' => '7109', 'name' => 'Kepulauan Siau Tagulandang Biaro (Sitaro)']);
        DB::table('cities')->insert(['id' => '8205', 'name' => 'Kepulauan Sula']);
        DB::table('cities')->insert(['id' => '7104', 'name' => 'Kepulauan Talaud']);
        DB::table('cities')->insert(['id' => '8103', 'name' => 'Kepulauan Tanimbar (Maluku Tenggara Barat)']);
        DB::table('cities')->insert(['id' => '9105', 'name' => 'Kepulauan Yapen']);
        DB::table('cities')->insert(['id' => '1501', 'name' => 'Kerinci']);
        DB::table('cities')->insert(['id' => '6104', 'name' => 'Ketapang']);
        DB::table('cities')->insert(['id' => '3310', 'name' => 'Klaten']);
        DB::table('cities')->insert(['id' => '5105', 'name' => 'Klungkung']);
        DB::table('cities')->insert(['id' => '7401', 'name' => 'Kolaka']);
        DB::table('cities')->insert(['id' => '7411', 'name' => 'Kolaka Timur']);
        DB::table('cities')->insert(['id' => '7408', 'name' => 'Kolaka Utara']);
        DB::table('cities')->insert(['id' => '7402', 'name' => 'Konawe']);
        DB::table('cities')->insert(['id' => '7412', 'name' => 'Konawe Kepulauan']);
        DB::table('cities')->insert(['id' => '7405', 'name' => 'Konawe Selatan']);
        DB::table('cities')->insert(['id' => '7409', 'name' => 'Konawe Utara']);
        DB::table('cities')->insert(['id' => '6302', 'name' => 'Kotabaru']);
        DB::table('cities')->insert(['id' => '7174', 'name' => 'Kotamobagu']);
        DB::table('cities')->insert(['id' => '6201', 'name' => 'Kotawaringin Barat']);
        DB::table('cities')->insert(['id' => '6202', 'name' => 'Kotawaringin Timur']);
        DB::table('cities')->insert(['id' => '1409', 'name' => 'Kuantan Singingi']);
        DB::table('cities')->insert(['id' => '6112', 'name' => 'Kubu Raya']);
        DB::table('cities')->insert(['id' => '3319', 'name' => 'Kudus']);
        DB::table('cities')->insert(['id' => '3401', 'name' => 'Kulon Progo']);
        DB::table('cities')->insert(['id' => '3208', 'name' => 'Kuningan']);
        DB::table('cities')->insert(['id' => '5301', 'name' => 'Kupang']);
        DB::table('cities')->insert(['id' => '6407', 'name' => 'Kutai Barat']);
        DB::table('cities')->insert(['id' => '6402', 'name' => 'Kutai Kartanegara']);
        DB::table('cities')->insert(['id' => '6408', 'name' => 'Kutai Timur']);
        DB::table('cities')->insert(['id' => '1210', 'name' => 'Labuhanbatu']);
        DB::table('cities')->insert(['id' => '1222', 'name' => 'Labuhanbatu Selatan']);
        DB::table('cities')->insert(['id' => '1223', 'name' => 'Labuhanbatu Utara']);
        DB::table('cities')->insert(['id' => '1604', 'name' => 'Lahat']);
        DB::table('cities')->insert(['id' => '6209', 'name' => 'Lamandau']);
        DB::table('cities')->insert(['id' => '3524', 'name' => 'Lamongan']);
        DB::table('cities')->insert(['id' => '1804', 'name' => 'Lampung Barat']);
        DB::table('cities')->insert(['id' => '1801', 'name' => 'Lampung Selatan']);
        DB::table('cities')->insert(['id' => '1802', 'name' => 'Lampung Tengah']);
        DB::table('cities')->insert(['id' => '1807', 'name' => 'Lampung Timur']);
        DB::table('cities')->insert(['id' => '1803', 'name' => 'Lampung Utara']);
        DB::table('cities')->insert(['id' => '6108', 'name' => 'Landak']);
        DB::table('cities')->insert(['id' => '1205', 'name' => 'Langkat']);
        DB::table('cities')->insert(['id' => '1174', 'name' => 'Langsa']);
        DB::table('cities')->insert(['id' => '9507', 'name' => 'Lanny Jaya']);
        DB::table('cities')->insert(['id' => '3602', 'name' => 'Lebak']);
        DB::table('cities')->insert(['id' => '1707', 'name' => 'Lebong']);
        DB::table('cities')->insert(['id' => '5313', 'name' => 'Lembata']);
        DB::table('cities')->insert(['id' => '1173', 'name' => 'Lhokseumawe']);
        DB::table('cities')->insert(['id' => '1307', 'name' => 'Lima Puluh Kota']);
        DB::table('cities')->insert(['id' => '2104', 'name' => 'Lingga']);
        DB::table('cities')->insert(['id' => '5201', 'name' => 'Lombok Barat']);
        DB::table('cities')->insert(['id' => '5202', 'name' => 'Lombok Tengah']);
        DB::table('cities')->insert(['id' => '5203', 'name' => 'Lombok Timur']);
        DB::table('cities')->insert(['id' => '5208', 'name' => 'Lombok Utara']);
        DB::table('cities')->insert(['id' => '1673', 'name' => 'Lubuk Linggau']);
        DB::table('cities')->insert(['id' => '3508', 'name' => 'Lumajang']);
        DB::table('cities')->insert(['id' => '7317', 'name' => 'Luwu']);
        DB::table('cities')->insert(['id' => '7324', 'name' => 'Luwu Timur']);
        DB::table('cities')->insert(['id' => '7322', 'name' => 'Luwu Utara']);
        DB::table('cities')->insert(['id' => '3519', 'name' => 'Madiun']);
        DB::table('cities')->insert(['id' => '3308', 'name' => 'Magelang']);
        DB::table('cities')->insert(['id' => '3520', 'name' => 'Magetan']);
        DB::table('cities')->insert(['id' => '6411', 'name' => 'Mahakam Ulu']);
        DB::table('cities')->insert(['id' => '3210', 'name' => 'Majalengka']);
        DB::table('cities')->insert(['id' => '7605', 'name' => 'Majene']);
        DB::table('cities')->insert(['id' => '7371', 'name' => 'Makassar']);
        DB::table('cities')->insert(['id' => '5321', 'name' => 'Malaka']);
        DB::table('cities')->insert(['id' => '3507', 'name' => 'Malang']);
        DB::table('cities')->insert(['id' => '6502', 'name' => 'Malinau']);
        DB::table('cities')->insert(['id' => '8108', 'name' => 'Maluku Barat Daya']);
        DB::table('cities')->insert(['id' => '8101', 'name' => 'Maluku Tengah']);
        DB::table('cities')->insert(['id' => '8102', 'name' => 'Maluku Tenggara']);
        DB::table('cities')->insert(['id' => '7603', 'name' => 'Mamasa']);
        DB::table('cities')->insert(['id' => '9120', 'name' => 'Mamberamo Raya']);
        DB::table('cities')->insert(['id' => '9505', 'name' => 'Mamberamo Tengah']);
        DB::table('cities')->insert(['id' => '7602', 'name' => 'Mamuju']);
        DB::table('cities')->insert(['id' => '7606', 'name' => 'Mamuju Tengah']);
        DB::table('cities')->insert(['id' => '7171', 'name' => 'Manado']);
        DB::table('cities')->insert(['id' => '1213', 'name' => 'Mandailing Natal']);
        DB::table('cities')->insert(['id' => '5310', 'name' => 'Manggarai']);
        DB::table('cities')->insert(['id' => '5315', 'name' => 'Manggarai Barat']);
        DB::table('cities')->insert(['id' => '5319', 'name' => 'Manggarai Timur']);
        DB::table('cities')->insert(['id' => '9202', 'name' => 'Manokwari']);
        DB::table('cities')->insert(['id' => '9211', 'name' => 'Manokwari Selatan']);
        DB::table('cities')->insert(['id' => '9303', 'name' => 'Mappi']);
        DB::table('cities')->insert(['id' => '7309', 'name' => 'Maros']);
        DB::table('cities')->insert(['id' => '5271', 'name' => 'Mataram']);
        DB::table('cities')->insert(['id' => '9210', 'name' => 'Maybrat']);
        DB::table('cities')->insert(['id' => '1271', 'name' => 'Medan']);
        DB::table('cities')->insert(['id' => '6110', 'name' => 'Melawi']);
        DB::table('cities')->insert(['id' => '6102', 'name' => 'Mempawah']);
        DB::table('cities')->insert(['id' => '1502', 'name' => 'Merangin']);
        DB::table('cities')->insert(['id' => '9301', 'name' => 'Merauke']);
        DB::table('cities')->insert(['id' => '1811', 'name' => 'Mesuji']);
        DB::table('cities')->insert(['id' => '1872', 'name' => 'Metro']);
        DB::table('cities')->insert(['id' => '9404', 'name' => 'Mimika']);
        DB::table('cities')->insert(['id' => '7102', 'name' => 'Minahasa']);
        DB::table('cities')->insert(['id' => '7105', 'name' => 'Minahasa Selatan']);
        DB::table('cities')->insert(['id' => '7107', 'name' => 'Minahasa Tenggara']);
        DB::table('cities')->insert(['id' => '7106', 'name' => 'Minahasa Utara']);
        DB::table('cities')->insert(['id' => '3516', 'name' => 'Mojokerto']);
        DB::table('cities')->insert(['id' => '7206', 'name' => 'Morowali']);
        DB::table('cities')->insert(['id' => '7212', 'name' => 'Morowali Utara']);
        DB::table('cities')->insert(['id' => '1603', 'name' => 'Muara Enim']);
        DB::table('cities')->insert(['id' => '1505', 'name' => 'Muaro Jambi']);
        DB::table('cities')->insert(['id' => '1706', 'name' => 'Muko Muko']);
        DB::table('cities')->insert(['id' => '7403', 'name' => 'Muna']);
        DB::table('cities')->insert(['id' => '7413', 'name' => 'Muna Barat']);
        DB::table('cities')->insert(['id' => '6212', 'name' => 'Murung Raya']);
        DB::table('cities')->insert(['id' => '1606', 'name' => 'Musi Banyuasin']);
        DB::table('cities')->insert(['id' => '1605', 'name' => 'Musi Rawas']);
        DB::table('cities')->insert(['id' => '1613', 'name' => 'Musi Rawas Utara']);
        DB::table('cities')->insert(['id' => '9401', 'name' => 'Nabire']);
        DB::table('cities')->insert(['id' => '1115', 'name' => 'Nagan Raya']);
        DB::table('cities')->insert(['id' => '5316', 'name' => 'Nagekeo']);
        DB::table('cities')->insert(['id' => '2103', 'name' => 'Natuna']);
        DB::table('cities')->insert(['id' => '9508', 'name' => 'Nduga']);
        DB::table('cities')->insert(['id' => '5309', 'name' => 'Ngada']);
        DB::table('cities')->insert(['id' => '3518', 'name' => 'Nganjuk']);
        DB::table('cities')->insert(['id' => '3521', 'name' => 'Ngawi']);
        DB::table('cities')->insert(['id' => '1204', 'name' => 'Nias']);
        DB::table('cities')->insert(['id' => '1225', 'name' => 'Nias Barat']);
        DB::table('cities')->insert(['id' => '1214', 'name' => 'Nias Selatan']);
        DB::table('cities')->insert(['id' => '1224', 'name' => 'Nias Utara']);
        DB::table('cities')->insert(['id' => '6503', 'name' => 'Nunukan']);
        DB::table('cities')->insert(['id' => '1610', 'name' => 'Ogan Ilir']);
        DB::table('cities')->insert(['id' => '1602', 'name' => 'Ogan Komering Ilir']);
        DB::table('cities')->insert(['id' => '1601', 'name' => 'Ogan Komering Ulu']);
        DB::table('cities')->insert(['id' => '1609', 'name' => 'Ogan Komering Ulu Selatan']);
        DB::table('cities')->insert(['id' => '1608', 'name' => 'Ogan Komering Ulu Timur']);
        DB::table('cities')->insert(['id' => '3501', 'name' => 'Pacitan']);
        DB::table('cities')->insert(['id' => '1371', 'name' => 'Padang']);
        DB::table('cities')->insert(['id' => '1221', 'name' => 'Padang Lawas']);
        DB::table('cities')->insert(['id' => '1220', 'name' => 'Padang Lawas Utara']);
        DB::table('cities')->insert(['id' => '1374', 'name' => 'Padang Panjang']);
        DB::table('cities')->insert(['id' => '1305', 'name' => 'Padang Pariaman']);
        DB::table('cities')->insert(['id' => '1277', 'name' => 'Padangsidimpuan']);
        DB::table('cities')->insert(['id' => '1672', 'name' => 'Pagar Alam']);
        DB::table('cities')->insert(['id' => '7504', 'name' => 'Pahuwato']);
        DB::table('cities')->insert(['id' => '1215', 'name' => 'Pakpak Bharat']);
        DB::table('cities')->insert(['id' => '6271', 'name' => 'Palangkaraya']);
        DB::table('cities')->insert(['id' => '1671', 'name' => 'Palembang']);
        DB::table('cities')->insert(['id' => '7373', 'name' => 'Palopo']);
        DB::table('cities')->insert(['id' => '7271', 'name' => 'Palu']);
        DB::table('cities')->insert(['id' => '3528', 'name' => 'Pamekasan']);
        DB::table('cities')->insert(['id' => '3601', 'name' => 'Pandeglang']);
        DB::table('cities')->insert(['id' => '3218', 'name' => 'Pangandaran']);
        DB::table('cities')->insert(['id' => '7310', 'name' => 'Pangkajene Kepulauan']);
        DB::table('cities')->insert(['id' => '1971', 'name' => 'Pangkal Pinang']);
        DB::table('cities')->insert(['id' => '9403', 'name' => 'Paniai']);
        DB::table('cities')->insert(['id' => '7372', 'name' => 'Pare Pare']);
        DB::table('cities')->insert(['id' => '1377', 'name' => 'Pariaman']);
        DB::table('cities')->insert(['id' => '7208', 'name' => 'Parigi Moutong']);
        DB::table('cities')->insert(['id' => '1308', 'name' => 'Pasaman']);
        DB::table('cities')->insert(['id' => '1312', 'name' => 'Pasaman Barat']);
        DB::table('cities')->insert(['id' => '7601', 'name' => 'Pasangkayu (Mamuju Utara)']);
        DB::table('cities')->insert(['id' => '6401', 'name' => 'Paser']);
        DB::table('cities')->insert(['id' => '3514', 'name' => 'Pasuruan']);
        DB::table('cities')->insert(['id' => '3318', 'name' => 'Pati']);
        DB::table('cities')->insert(['id' => '1376', 'name' => 'Payakumbuh']);
        DB::table('cities')->insert(['id' => '9212', 'name' => 'Pegunungan Arfak']);
        DB::table('cities')->insert(['id' => '9502', 'name' => 'Pegunungan Bintang']);
        DB::table('cities')->insert(['id' => '3326', 'name' => 'Pekalongan']);
        DB::table('cities')->insert(['id' => '1471', 'name' => 'Pekanbaru']);
        DB::table('cities')->insert(['id' => '1405', 'name' => 'Pelalawan']);
        DB::table('cities')->insert(['id' => '3327', 'name' => 'Pemalang']);
        DB::table('cities')->insert(['id' => '1272', 'name' => 'Pematangsiantar']);
        DB::table('cities')->insert(['id' => '6409', 'name' => 'Penajam Paser Utara']);
        DB::table('cities')->insert(['id' => '1612', 'name' => 'Penukal Abab Lematang Ilir']);
        DB::table('cities')->insert(['id' => '1809', 'name' => 'Pesawaran']);
        DB::table('cities')->insert(['id' => '1813', 'name' => 'Pesisir Barat']);
        DB::table('cities')->insert(['id' => '1301', 'name' => 'Pesisir Selatan']);
        DB::table('cities')->insert(['id' => '1107', 'name' => 'Pidie']);
        DB::table('cities')->insert(['id' => '1118', 'name' => 'Pidie Jaya']);
        DB::table('cities')->insert(['id' => '7315', 'name' => 'Pinrang']);
        DB::table('cities')->insert(['id' => '7604', 'name' => 'Polewali Mandar']);
        DB::table('cities')->insert(['id' => '3502', 'name' => 'Ponorogo']);
        DB::table('cities')->insert(['id' => '6171', 'name' => 'Pontianak']);
        DB::table('cities')->insert(['id' => '7202', 'name' => 'Poso']);
        DB::table('cities')->insert(['id' => '1674', 'name' => 'Prabumulih']);
        DB::table('cities')->insert(['id' => '1810', 'name' => 'Pringsewu']);
        DB::table('cities')->insert(['id' => '3513', 'name' => 'Probolinggo']);
        DB::table('cities')->insert(['id' => '6211', 'name' => 'Pulang Pisau']);
        DB::table('cities')->insert(['id' => '8207', 'name' => 'Pulau Morotai']);
        DB::table('cities')->insert(['id' => '8208', 'name' => 'Pulau Taliabu']);
        DB::table('cities')->insert(['id' => '9405', 'name' => 'Puncak']);
        DB::table('cities')->insert(['id' => '9402', 'name' => 'Puncak Jaya']);
        DB::table('cities')->insert(['id' => '3303', 'name' => 'Purbalingga']);
        DB::table('cities')->insert(['id' => '3214', 'name' => 'Purwakarta']);
        DB::table('cities')->insert(['id' => '3306', 'name' => 'Purworejo']);
        DB::table('cities')->insert(['id' => '9205', 'name' => 'Raja Ampat']);
        DB::table('cities')->insert(['id' => '1702', 'name' => 'Rejang Lebong']);
        DB::table('cities')->insert(['id' => '3317', 'name' => 'Rembang']);
        DB::table('cities')->insert(['id' => '1407', 'name' => 'Rokan Hilir']);
        DB::table('cities')->insert(['id' => '1406', 'name' => 'Rokan Hulu']);
        DB::table('cities')->insert(['id' => '5314', 'name' => 'Rote Ndao']);
        DB::table('cities')->insert(['id' => '1172', 'name' => 'Sabang']);
        DB::table('cities')->insert(['id' => '5320', 'name' => 'Sabu Raijua']);
        DB::table('cities')->insert(['id' => '3373', 'name' => 'Salatiga']);
        DB::table('cities')->insert(['id' => '6472', 'name' => 'Samarinda']);
        DB::table('cities')->insert(['id' => '6101', 'name' => 'Sambas']);
        DB::table('cities')->insert(['id' => '1217', 'name' => 'Samosir']);
        DB::table('cities')->insert(['id' => '3527', 'name' => 'Sampang']);
        DB::table('cities')->insert(['id' => '6103', 'name' => 'Sanggau']);
        DB::table('cities')->insert(['id' => '9110', 'name' => 'Sarmi']);
        DB::table('cities')->insert(['id' => '1503', 'name' => 'Sarolangun']);
        DB::table('cities')->insert(['id' => '1373', 'name' => 'Sawahlunto']);
        DB::table('cities')->insert(['id' => '6109', 'name' => 'Sekadau']);
        DB::table('cities')->insert(['id' => '1705', 'name' => 'Seluma']);
        DB::table('cities')->insert(['id' => '3322', 'name' => 'Semarang']);
        DB::table('cities')->insert(['id' => '8106', 'name' => 'Seram Bagian Barat']);
        DB::table('cities')->insert(['id' => '8105', 'name' => 'Seram Bagian Timur']);
        DB::table('cities')->insert(['id' => '3673', 'name' => 'Serang']);
        DB::table('cities')->insert(['id' => '1218', 'name' => 'Serdang Bedagai']);
        DB::table('cities')->insert(['id' => '6207', 'name' => 'Seruyan']);
        DB::table('cities')->insert(['id' => '1408', 'name' => 'Siak']);
        DB::table('cities')->insert(['id' => '1273', 'name' => 'Sibolga']);
        DB::table('cities')->insert(['id' => '7314', 'name' => 'Sidenreng Rappang']);
        DB::table('cities')->insert(['id' => '3515', 'name' => 'Sidoarjo']);
        DB::table('cities')->insert(['id' => '7210', 'name' => 'Sigi']);
        DB::table('cities')->insert(['id' => '1303', 'name' => 'Sijunjung']);
        DB::table('cities')->insert(['id' => '5307', 'name' => 'Sikka']);
        DB::table('cities')->insert(['id' => '1208', 'name' => 'Simalungun']);
        DB::table('cities')->insert(['id' => '1109', 'name' => 'Simeulue']);
        DB::table('cities')->insert(['id' => '6172', 'name' => 'Singkawang']);
        DB::table('cities')->insert(['id' => '7307', 'name' => 'Sinjai']);
        DB::table('cities')->insert(['id' => '6105', 'name' => 'Sintang']);
        DB::table('cities')->insert(['id' => '3512', 'name' => 'Situbondo']);
        DB::table('cities')->insert(['id' => '3404', 'name' => 'Sleman']);
        DB::table('cities')->insert(['id' => '1302', 'name' => 'Solok']);
        DB::table('cities')->insert(['id' => '1311', 'name' => 'Solok Selatan']);
        DB::table('cities')->insert(['id' => '7312', 'name' => 'Soppeng']);
        DB::table('cities')->insert(['id' => '9201', 'name' => 'Sorong']);
        DB::table('cities')->insert(['id' => '9204', 'name' => 'Sorong Selatan']);
        DB::table('cities')->insert(['id' => '3314', 'name' => 'Sragen']);
        DB::table('cities')->insert(['id' => '3213', 'name' => 'Subang']);
        DB::table('cities')->insert(['id' => '1175', 'name' => 'Subulussalam']);
        DB::table('cities')->insert(['id' => '3272', 'name' => 'Sukabumi']);
        DB::table('cities')->insert(['id' => '6208', 'name' => 'Sukamara']);
        DB::table('cities')->insert(['id' => '3311', 'name' => 'Sukoharjo']);
        DB::table('cities')->insert(['id' => '5312', 'name' => 'Sumba Barat']);
        DB::table('cities')->insert(['id' => '5318', 'name' => 'Sumba Barat Daya']);
        DB::table('cities')->insert(['id' => '5317', 'name' => 'Sumba Tengah']);
        DB::table('cities')->insert(['id' => '5311', 'name' => 'Sumba Timur']);
        DB::table('cities')->insert(['id' => '5204', 'name' => 'Sumbawa']);
        DB::table('cities')->insert(['id' => '5207', 'name' => 'Sumbawa Barat']);
        DB::table('cities')->insert(['id' => '3211', 'name' => 'Sumedang']);
        DB::table('cities')->insert(['id' => '3529', 'name' => 'Sumenep']);
        DB::table('cities')->insert(['id' => '1572', 'name' => 'Sungai Penuh']);
        DB::table('cities')->insert(['id' => '9119', 'name' => 'Supiori']);
        DB::table('cities')->insert(['id' => '3578', 'name' => 'Surabaya']);
        DB::table('cities')->insert(['id' => '3372', 'name' => 'Surakarta']);
        DB::table('cities')->insert(['id' => '6309', 'name' => 'Tabalong']);
        DB::table('cities')->insert(['id' => '5102', 'name' => 'Tabanan']);
        DB::table('cities')->insert(['id' => '7305', 'name' => 'Takalar']);
        DB::table('cities')->insert(['id' => '9209', 'name' => 'Tambrauw']);
        DB::table('cities')->insert(['id' => '6504', 'name' => 'Tana Tidung']);
        DB::table('cities')->insert(['id' => '7318', 'name' => 'Tana Toraja']);
        DB::table('cities')->insert(['id' => '6310', 'name' => 'Tanah Bumbu']);
        DB::table('cities')->insert(['id' => '1304', 'name' => 'Tanah Datar']);
        DB::table('cities')->insert(['id' => '6301', 'name' => 'Tanah Laut']);
        DB::table('cities')->insert(['id' => '3671', 'name' => 'Tangerang']);
        DB::table('cities')->insert(['id' => '3674', 'name' => 'Tangerang Selatan']);
        DB::table('cities')->insert(['id' => '1806', 'name' => 'Tanggamus']);
        DB::table('cities')->insert(['id' => '1274', 'name' => 'Tanjung Balai']);
        DB::table('cities')->insert(['id' => '1506', 'name' => 'Tanjung Jabung Barat']);
        DB::table('cities')->insert(['id' => '1507', 'name' => 'Tanjung Jabung Timur']);
        DB::table('cities')->insert(['id' => '2172', 'name' => 'Tanjung Pinang']);
        DB::table('cities')->insert(['id' => '1203', 'name' => 'Tapanuli Selatan']);
        DB::table('cities')->insert(['id' => '1201', 'name' => 'Tapanuli Tengah']);
        DB::table('cities')->insert(['id' => '1202', 'name' => 'Tapanuli Utara']);
        DB::table('cities')->insert(['id' => '6305', 'name' => 'Tapin']);
        DB::table('cities')->insert(['id' => '6571', 'name' => 'Tarakan']);
        DB::table('cities')->insert(['id' => '3278', 'name' => 'Tasikmalaya']);
        DB::table('cities')->insert(['id' => '1276', 'name' => 'Tebing Tinggi']);
        DB::table('cities')->insert(['id' => '1509', 'name' => 'Tebo']);
        DB::table('cities')->insert(['id' => '3328', 'name' => 'Tegal']);
        DB::table('cities')->insert(['id' => '9206', 'name' => 'Teluk Bintuni']);
        DB::table('cities')->insert(['id' => '9207', 'name' => 'Teluk Wondama']);
        DB::table('cities')->insert(['id' => '3323', 'name' => 'Temanggung']);
        DB::table('cities')->insert(['id' => '8271', 'name' => 'Ternate']);
        DB::table('cities')->insert(['id' => '8272', 'name' => 'Tidore Kepulauan']);
        DB::table('cities')->insert(['id' => '5302', 'name' => 'Timor Tengah Selatan']);
        DB::table('cities')->insert(['id' => '5303', 'name' => 'Timor Tengah Utara']);
        DB::table('cities')->insert(['id' => '1212', 'name' => 'Toba']);
        DB::table('cities')->insert(['id' => '7209', 'name' => 'Tojo Una Una']);
        DB::table('cities')->insert(['id' => '7204', 'name' => 'Toli Toli']);
        DB::table('cities')->insert(['id' => '9504', 'name' => 'Tolikara']);
        DB::table('cities')->insert(['id' => '7173', 'name' => 'Tomohon']);
        DB::table('cities')->insert(['id' => '7326', 'name' => 'Toraja Utara']);
        DB::table('cities')->insert(['id' => '3503', 'name' => 'Trenggalek']);
        DB::table('cities')->insert(['id' => '8172', 'name' => 'Tual']);
        DB::table('cities')->insert(['id' => '3523', 'name' => 'Tuban']);
        DB::table('cities')->insert(['id' => '1805', 'name' => 'Tulang Bawang']);
        DB::table('cities')->insert(['id' => '1812', 'name' => 'Tulang Bawang Barat']);
        DB::table('cities')->insert(['id' => '3504', 'name' => 'Tulungagung']);
        DB::table('cities')->insert(['id' => '7313', 'name' => 'Wajo']);
        DB::table('cities')->insert(['id' => '7407', 'name' => 'Wakatobi']);
        DB::table('cities')->insert(['id' => '9115', 'name' => 'Waropen']);
        DB::table('cities')->insert(['id' => '1808', 'name' => 'Way Kanan']);
        DB::table('cities')->insert(['id' => '3312', 'name' => 'Wonogiri']);
        DB::table('cities')->insert(['id' => '3307', 'name' => 'Wonosobo']);
        DB::table('cities')->insert(['id' => '9503', 'name' => 'Yahukimo']);
        DB::table('cities')->insert(['id' => '9506', 'name' => 'Yalimo']);
        DB::table('cities')->insert(['id' => '3471', 'name' => 'Yogyakarta']);
    }
}
